version: "3.7"
services:
  dbsql:
    image: postgres:13.4-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./backend/db-model:/docker-entrypoint-initdb.d/
      - ./backend/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile 
    depends_on:
      - dbsql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: dbsql
    restart: always
    volumes:
      - ./backend/src:/home/node/src
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile 
    depends_on:
      - backend
      - dbsql
    restart: always
    volumes:
      - ./frontend/public:/home/node/public
      - ./frontend/src:/home/node/src
    ports:
      - "80:3000"
    